version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    command: 
    - |
      gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
      celery -A app.celery worker --loglevel=info
    depends_on:
      - redis

  
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    expose:
      - '80'
      - '443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask_app


    
  redis:
    image: redis:6-alpine

