name: Deploy to EC2
on:
  push:
    branches: [ "main" ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      
    - name: create env file
      run: |
        touch .env
        echo "FLASK_API_KEY=$FLASK_API_KEY" >> .env
        echo "AWS_ACCESS_KEY=$AWS_ACCESS_KEY" >> .env
        echo "AWS_SECRET_KEY=$AWS_SECRET_KEY" >> .env
        echo "BUCKET_NAME=$BUCKET_NAME" >> .env
        echo "X_OCR_SECRET=$X_OCR_SECRET" >> .env
      env:
        FLASK_API_KEY: ${{ secrets.FLASK_API_KEY }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        X_OCR_SECRET: ${{ secrets.X_OCR_SECRET }}
        
    # ec2에서 기존 디렉토리 삭제 & 새로운 디렉토리 생성
    - name: remove existing directory on server & create new remote directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: 22222
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          sudo rm -rf /home/ubuntu/srv/nlp_clova
          mkdir -p /home/ubuntu/srv/nlp_clova
        
    # ec2에 소스코드 복사
    - name: copy source via ssh key
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        remote_path: /home/ubuntu/srv/nlp_clova
        remote_host: ${{ secrets.HOST }}
        remote_user: ubuntu
        remote_key: ${{ secrets.PRIVATE_KEY }}
    
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.HOST }}
       port: 22222
       username: ubuntu
       key: ${{ secrets.PRIVATE_KEY }}
       script: |
          sh /home/ubuntu/srv/nlp_clova/run_docker.sh

        
    
